version: '3.8'

services:
  node1:
    image: bitnami/mysql:8.0
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_REPLICATION_MODE=master
      - MYSQL_REPLICATION_USER=repl_user
      - MYSQL_REPLICATION_PASSWORD=repl_password
    volumes:
      - mysql_node1_data:/bitnami/mysql/data
    networks:
      - wp_network

  node2:
    image: bitnami/mysql:8.0
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_REPLICATION_MODE=slave
      - MYSQL_REPLICATION_USER=repl_user
      - MYSQL_REPLICATION_PASSWORD=repl_password
      - MYSQL_MASTER_HOST=node1
      - MYSQL_MASTER_PORT_NUMBER=3306
      - MYSQL_MASTER_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql_node2_data:/bitnami/mysql/data
    networks:
      - wp_network
    depends_on:
      - node1

  node3:
    image: bitnami/mysql:8.0
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_REPLICATION_MODE=slave
      - MYSQL_REPLICATION_USER=repl_user
      - MYSQL_REPLICATION_PASSWORD=repl_password
      - MYSQL_MASTER_HOST=node1
      - MYSQL_MASTER_PORT_NUMBER=3306
      - MYSQL_MASTER_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql_node3_data:/bitnami/mysql/data
    networks:
      - wp_network
    depends_on:
      - node1

  wordpress:
    image: wordpress:latest
    depends_on:
      - node1
      - node2
      - node3
    ports:
      - "8080:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: node1
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - wp_network

  mysqld_exporter_node1:
    image: prom/mysqld-exporter:latest
    environment:
      - DATA_SOURCE_NAME=wordpress:${MYSQL_PASSWORD}@tcp(node1:3306)/
    depends_on:
      - node1
    networks:
      - wp_network

  mysqld_exporter_node2:
    image: prom/mysqld-exporter:latest
    environment:
      - DATA_SOURCE_NAME=wordpress:${MYSQL_PASSWORD}@tcp(node2:3306)/
    depends_on:
      - node2
    networks:
      - wp_network

  mysqld_exporter_node3:
    image: prom/mysqld-exporter:latest
    environment:
      - DATA_SOURCE_NAME=wordpress:${MYSQL_PASSWORD}@tcp(node3:3306)/
    depends_on:
      - node3
    networks:
      - wp_network

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    networks:
      - wp_network

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - wp_network
    depends_on:
      - prometheus

volumes:
  mysql_node1_data:
  mysql_node2_data:
  mysql_node3_data:
  wordpress_data:

networks:
  wp_network:
    driver: bridge
