---
- name: Setup ansible user
  hosts: wordpress_servers
  become: true
  tasks:
    - name: Create ansible user
      user:
        name: ansible
        shell: /bin/bash
        groups: sudo
        append: yes
        create_home: yes
        state: present

    - name: Set up sudo for ansible user
      copy:
        content: "ansible ALL=(ALL) NOPASSWD:ALL"
        dest: /etc/sudoers.d/ansible
        mode: 0440
        validate: /usr/sbin/visudo -cf %s

    # - name: Add authorized key
    #   authorized_key:
    #     user: ansible
    #     state: present
    #     key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

- name: Deploy WordPress with Docker
  hosts: wordpress_servers
  become: true
  vars_files:
    - vars/main.yml

  tasks:
    - name: Install required packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
          - software-properties-common
        state: present
        update_cache: yes

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        state: present
        filename: docker

    - name: Install Docker and Docker Compose plugin
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
        state: present
        update_cache: yes

    - name: Create docker group
      group:
        name: docker
        state: present

    - name: Create project user
      user:
        name: "{{ project_user }}"
        group: "{{ project_group }}"
        home: "{{ project_home }}"
        shell: /bin/bash
        create_home: yes
        state: present

    - name: Add user to docker group
      user:
        name: "{{ project_user }}"
        groups: docker
        append: yes

    - name: Wait for group changes to take effect
      meta: flush_handlers

    - name: Create project directory
      file:
        path: "{{ project_dir }}"
        state: directory
        mode: '0755'
        owner: "{{ project_user }}"
        group: "{{ project_group }}"

    - name: Copy prometheus config
      copy:
        src: prometheus.yml
        dest: "{{ project_dir }}/prometheus.yml"
        owner: "{{ project_user }}"
        group: "{{ project_group }}"
        mode: '0644'

    - name: Copy docker-compose.yml
      copy:
        src: docker-compose.yml
        dest: "{{ project_dir }}/docker-compose.yml"
        owner: "{{ project_user }}"
        group: "{{ project_group }}"
        mode: '0644'

    - name: Copy MySQL configuration
      copy:
        src: mysql.cnf
        dest: "{{ project_dir }}/mysql.cnf"
        owner: "{{ project_user }}"
        group: "{{ project_group }}"
        mode: '0644'

    - name: Copy environment file
      copy:
        src: .env
        dest: "{{ project_dir }}/.env"
        owner: "{{ project_user }}"
        group: "{{ project_group }}"
        mode: '0600'

    - name: Остановить и удалить старые сервисы (если нужно)
      shell: docker compose -f {{ project_dir }}/docker-compose.yml down
      args:
        chdir: "{{ project_dir }}"

    - name: Запустить основной стек (WordPress, БД и т.д.)
      shell: docker compose -f {{ project_dir }}/docker-compose.yml up -d
      args:
        chdir: "{{ project_dir }}"

    - name: Шаблонизировать docker-compose-monitoring.yml
      template:
        src: docker-compose-monitoring.yml.j2
        dest: "{{ project_dir }}/docker-compose-monitoring.yml"
        mode: '0644'

    - name: Шаблонизировать prometheus.yml
      template:
        src: prometheus.yml.j2
        dest: "{{ project_dir }}/prometheus.yml"
        mode: '0644'

    - name: Запустить мониторинг через docker compose
      shell: docker compose -f {{ project_dir }}/docker-compose-monitoring.yml up -d
      args:
        chdir: "{{ project_dir }}"
